parameters:
    app.deposit_amount: 50
    app.contact_phone: '+216 71 000 000'
    app.bank_name: 'Banque de Tunisie'
    app.bank_rib: '08 006 0123456789 12'
    app.bank_swift: 'BTUNTNTX'
    app.solidarity_fund_amount: '%env(int:SOLIDARITY_FUND_AMOUNT)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            int $depositAmount: '%app.deposit_amount%'
            int $solidarityFundAmount: '%app.solidarity_fund_amount%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
